name: build

on:
  push:
    branches:
      - "**"

env:
  DOTNET_NOLOGO: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 2

      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          # key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
          # restore-keys: |
          #   ${{ runner.os }}-nuget

      - name: restore
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore ./MimeMapping.sln

      - name: test
        run: dotnet test --no-build ./MimeMapping.sln

      - name: Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # v3.1.1
        if: always() && matrix.os == 'ubuntu-latest'
        with:
          files: "**/TestResults/*/*.cobertura.xml"

  build:
    needs: [test]
    runs-on: windows-latest
    timeout-minutes: 15
    permissions:
      packages: write
      contents: write

    env:
      VO: true
      CONFIGURATION: Release

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          # key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
          # restore-keys: |
          #   ${{ runner.os }}-nuget

      - name: pack
        run: dotnet pack -o bin

      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: packages
          path: bin/*.nupkg
