name: build

on:
  push:
    branches:
      - '**'

env:
  DOTNET_NOLOGO: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 2

      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          # key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
          # restore-keys: |
          #   ${{ runner.os }}-nuget

      - name: restore
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore ./MimeMapping.sln

      - name: test
        run: dotnet test --no-build ./MimeMapping.sln

      - name: Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # v3.1.1
        with:
          files: '**/TestResults/*/*.cobertura.xml'

  build:
    needs: [test]
    runs-on: windows-latest
    timeout-minutes: 15
    permissions:
      packages: write
      contents: write

    env:
      VO: true
      CONFIGURATION: Release

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          # key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
          # restore-keys: |
          #   ${{ runner.os }}-nuget

      - name: pack
        run: dotnet pack -o bin

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: packages
          path: bin/*.nupkg
